#!/usr/bin/env bash
# Script that transfers a file from the client to a server

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi

# Check if the transfer was successful
if [ $? -eq 0 ]
then
  echo "TRANSFER WAS SUCCESSFULL"
else
  echo "TRANSFER FAILED"
fi
