#!/usr/bin/env bash
# Script that install Nginx on the server web-01

# Update the package and intall
sudo apt-get update
sudo apt-get -y install nginx

# Start nginx
sudo service nginx start 

# Allow incoming traffic for the Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

# Create  new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# redirecton to  youtube video
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
