#!/usr/bin/env bash
# Script that install Nginx on the server web-01

# Update the package and intall
sudo apt-get update
sudo apt-get -y install nginx

# Start nginx
sudo service nginx start 

# Allow incoming traffic for the Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Redirection to a youtube video
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Configure your Nginx server to have a custom 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

