#!/usr/bin/env bash
# Bash script debug nginx, make your fix short and sweet.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
