#!/usr/bin/env bash
# The Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed.

list=$(ls)
for index in $list; do
  echo "$index" | cut -d '-' -f2
done
