#!/usr/bin/env bash
# Bash script that configures the container to run as nginx user listening on port 8080.
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
