#!/usr/bin/env bash
# Bash script that runs Nginx as user and fix port from 80 to 8080
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
